### ISSUE TITLE
Catalogue cache gets invalidated half an hour after first access. 

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/iudx-rs-proxy#65]
https://github.com/datakaveri/iudx-rs-proxy/blob/15d73461606bb2f8320cea3c4baf334b68251954/src/main/java/iudx/rs/proxy/apiserver/service/CatalogueService.java#L44

- Because of this cat id is not found and the request against the  dataset fails. 
- Removing this line should make it work

**Comment by pranavrd** [comment]
Fixed in PR #66
